#' Create and open Excel workbook
#'
#' @param data data.frame
#' @param open_excel open workbook in Excel?
#'
#' @return workbook generated by openxlsx::createWorkbook
#'
#' @examples
#' view_in_excel(iris) # Excel opens
#'
#' @export
view_in_excel <- function(data, open_excel = TRUE) {
  fontSize <- 11
  fontName <- "Meiryo UI"
  startRow <- 3
  sheetName <- deparse(substitute(data))

  wb <- openxlsx::createWorkbook()
  openxlsx::addWorksheet(wb, sheetName = sheetName)
  openxlsx::modifyBaseFont(wb, fontSize = fontSize, fontName = fontName)
  header <- openxlsx::createStyle(
    fontName = fontName,
    fontSize = fontSize,
    fontColour = "white",
    border = "bottom",
    borderStyle = "double",
    borderColour = "black",
    fgFill = "#2f75b5",
    textDecoration = "bold"
  )
  openxlsx::freezePane(wb, sheet = sheetName, firstActiveRow = startRow + 1)
  openxlsx::writeData(wb, sheet = sheetName, x = data,
                      startRow = startRow, colNames = TRUE, headerStyle = header)

  if (open_excel) openxlsx::openXL(wb)

  invisible(wb)
}

#' Is an object the class of "try-error"?
#'
#' @examples
#' x <- try(stop())
#' is_try_error(x)
#'
#' @export
is_try_error <- function(x) inherits(x, "try-error")

#' Check if a data.frame is uniquely identified by a given set of columns
#'
#' @param data data.frame
#' @param ... columns
#'
#' @examples
#' x <- expand.grid(a = 1:2, b = letters[1:3])
#' x
#'
#' check_pk(x, a)
#' check_pk(x, a, b)
#'
#' @export
check_pk <- function(data, ...) nrow(data) == nrow(dplyr::distinct(dplyr::ungroup(data), ...))

#' Find duplicated rows in data.frame
#'
#' @examples
#' find_duplicated(mtcars, cyl)
#' @export
find_duplicated <- function(data, ...) {
  data %>%
    dplyr::group_by(...) %>%
    dplyr::mutate(n = dplyr::n()) %>%
    dplyr::filter(n > 1) %>%
    dplyr::ungroup() %>%
    dplyr::arrange(...)
}


#' Show table in ratio
#' @examples
#' x <- mtcars[, c("vs", "am")]
#' table(x)
#' table_ratio(x)
#'
#' @export
table_ratio <- function(..., digits = 2) {
  tbl <- table(...)
  round(tbl / sum(tbl), digits)
}


#' If x is with in a given range
#'
#' @examples
#' c(1, 1) %btw% list(c(0, 0), c(0, 1))
#' dplyr::filter(data.frame(x = 1:5, lw = 2, up = 4), x %btw% list(lw, up))
#'
#' @export
`%btw%` <- function(x, range) x >= range[[1L]] & x <= range[[2L]]

#' If x is between left and right
#' @examples
#' df <- data.frame(
#'   a = 1:5,
#'   lower = 2,
#'   upper = 4
#' )
#'
#' dplyr::filter(df, btw(a, lower, upper))
#'
#' @export
btw <- function(x, lower, upper) x >= lower & x <= upper

#' Draw a line
#' @export
draw_line <- function(sign = "-", n = 80) cat(rep(sign, n), "\n", sep = "")

#' Cross join
#' @examples
#' cross_join(data.frame(a = 1:2), data.frame(b = 1:3))
#' @export
cross_join <- function(x, y, ...) dplyr::inner_join(x, y, by = character(), ...)
